Areas/DHub/Models/Device.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace DroHub.Areas.DHub.Models
{
    public class Device {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Display(Name = "Serial Number")]
        [Required]
        public string SerialNumber { get; set; }

        public string ISO { get; set; }

        public string Apperture { get; set; }

        [Display(Name = "Focus Mode")]
        public string FocusMode { get; set; }

        [Display(Name = "Registration Date")]
        public DateTimeOffset CreationDate { get; set; }

        public string SubscriptionOrganizationName { get; set; }

        [JsonIgnore]
        public Subscription Subscription { get; set; }

        [JsonIgnore]
        public ICollection<DeviceConnection> DeviceConnections { get; set; }
    }
}

Areas/DHub/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using DroHub.Areas.DHub.API;
using DroHub.Areas.DHub.Helpers.ResourceAuthorizationHandlers;
using DroHub.Areas.DHub.Models;
using DroHub.Areas.Identity.Data;
using DroHub.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace DroHub.Areas.DHub.Controllers
{
    [Area("DHub")]
    public class DevicesController : AuthorizedController
    {
        private readonly ILogger<DevicesController> _logger;

        private readonly DeviceAPI _device_api;
        private readonly DeviceConnectionAPI _device_connection_api;
        private readonly SubscriptionAPI _subscription_api;

        public DevicesController(ILogger<DevicesController> logger,
            DeviceAPI device_api, DeviceConnectionAPI device_connection_api, SubscriptionAPI subscription_api)
        {
            _logger = logger;
            _device_api = device_api;
            _device_connection_api = device_connection_api;
            _subscription_api = subscription_api;
        }


        // GET: DroHub/GetDevicesList
        public async Task<IActionResult> GetDevicesList(){
            var device_list = await _device_api.getSubscribedDevices();

            if (device_list.Any() == false)
                return NoContent();

            return Json(device_list);
        }

        [NonAction]
        private async Task<IActionResult> GetTelemetry<TDroneTelemetry>([Required] int id,
            DeviceSessionExtensions.IncludeTelemetryDelegate<TDroneTelemetry> include_delegate)
            where TDroneTelemetry : IDroneTelemetry {
            if (!ModelState.IsValid) {
                return BadRequest();
            }
            try {
                var device_connection = await _device_connection_api.getDeviceConnection(id,
                    include_delegate);
                var r = device_connection
                    .GetType()
                    .GetProperties()
                    .SingleOrDefault(d => d.PropertyType == typeof(ICollection<TDroneTelemetry>))
                    ?.GetValue(device_connection, null) as ICollection<TDroneTelemetry>;

                return Json(r);
            }
            catch (DeviceAuthorizationException) {
                return Unauthorized();
            }
            catch (DeviceConnectionException e) {
                return StatusCode(503, new { message = e.Message});
            }
        }

        public async Task<IActionResult> GetDronePositions([Required]int id) {
            return await GetTelemetry(id, source =>
                source.Include(d => d.positions));
        }

        public async Task<IActionResult> GetDroneBatteryLevels([Required]int id) {
            return await GetTelemetry(id,source =>
                source.Include(d => d.battery_levels));
        }

        public async Task<IActionResult> GetCameraStates([Required]int id) {
            return await GetTelemetry(id, source =>
                source.Include(d => d.camera_states));
        }

        public async Task<IActionResult> GetGimbalStates([Required]int id) {
            return await GetTelemetry(id, source =>
                source.Include(d => d.gimbal_states));
        }

        public async Task<IActionResult> GetDroneRadioSignals([Required]int id) {
            return await GetTelemetry(id, source =>
                source.Include(d => d.radio_signals));
        }

        public async Task<IActionResult> GetDroneFlyingStates([Required]int id) {
            return await GetTelemetry(id, source =>
                source.Include(d => d.flying_states));
        }

        public async Task<IActionResult> GetDroneReplys([Required]int id) {
            return await GetTelemetry(id, source =>
                source.Include(d => d.drone_replies));
        }

        public async Task<IActionResult> GetDroneLiveVideoStateResults([Required]int id) {
            return await GetTelemetry(id, source =>
                source.Include(d => d.drone_video_states));
        }

        // GET: DroHub/Devices/Data/5
        public async Task<IActionResult> Data([Required]int id)
        {
            var device = await _device_api.getDeviceById(id);
            return (device == null ? (IActionResult) NotFound() : View(device));
        }

        public async Task<IActionResult> TakeOff([Required]int id) {
            try {
                var device = await _device_api.getDeviceById(id);
                await _device_connection_api.doDeviceAction(device, async client =>
                    await client.doTakeoffAsync(CancellationToken.None));
                return Ok();
            }
            catch (DeviceAuthorizationException e) {
                return Unauthorized(e.Message);
            }
            catch (DeviceConnectionException e) {
                return StatusCode(503, new { message = e.Message});
            }
        }
        public async Task<IActionResult> Land([Required]int id) {
            try {
                var device = await _device_api.getDeviceById(id);
                await _device_connection_api.doDeviceAction(device, async client =>
                    await client.doLandingAsync(CancellationToken.None));
                return Ok();
            }
            catch (DeviceAuthorizationException e) {
                return Unauthorized(e.Message);
            }
            catch (DeviceConnectionException e) {
                return StatusCode(503, new { message = e.Message});
            }
        }

        public async Task<IActionResult> ReturnToHome([Required]int id) {
            try {
                var device = await _device_api.getDeviceById(id);
                await _device_connection_api.doDeviceAction(device, async client =>
                    await client.doReturnToHomeAsync(CancellationToken.None));
                return Ok();
            }
            catch (DeviceAuthorizationException e) {
                return Unauthorized(e.Message);
            }
            catch (DeviceConnectionException e) {
                return StatusCode(503, new { message = e.Message});
            }
        }

        public async Task<IActionResult> SetCameraZoom([Required] string serial, [Required]double zoom_level) {
            if (!ModelState.IsValid)
                return BadRequest();

            try {
                var device = await _device_api.getDeviceBySerial(new DeviceAPI.DeviceSerial(serial));
                await _device_connection_api.doDeviceAction(device, async client =>
                    await client.setCameraZoomAsync(zoom_level, CancellationToken.None));
                return Ok();
            }
            catch (DeviceAuthorizationException e) {
                return Unauthorized(e.Message);
            }
            catch (DeviceConnectionException e) {
                return StatusCode(503, new { message = e.Message});
            }
        }

        public async Task<IActionResult> SetGimbalPitch([Required] string serial, [Required]double pitch) {
            if (!ModelState.IsValid)
                return BadRequest();

            try {
                var device = await _device_api.getDeviceBySerial(new DeviceAPI.DeviceSerial(serial));
                await _device_connection_api.doDeviceAction(device, async client =>
                    await client.setGimbalAttitudeAsync(pitch, 0.0f, 0.0f, CancellationToken.None));
                return Ok();
            }
            catch (DeviceAuthorizationException e) {
                return Unauthorized(e.Message);
            }
            catch (DeviceConnectionException e) {
                return StatusCode(503, new { message = e.Message});
            }
        }

        public async Task<IActionResult> MoveToPosition([Required]int id, [Required]float latitude,
            [Required]float longitude, [Required]float altitude, [Required]double heading) {
            try {
                var device = await _device_api.getDeviceById(id);
                var drone_request = new DroneRequestPosition
                {
                    Latitude = latitude,
                    Longitude = longitude,
                    Altitude = altitude,
                    Heading = heading,
                    Serial = device.SerialNumber
                };
                await _device_connection_api.doDeviceAction(device, async client =>
                    await client.moveToPositionAsync(drone_request, CancellationToken.None));
                return Ok();
            }
            catch (DeviceAuthorizationException e) {
                return Unauthorized(e.Message);
            }
            catch (DeviceConnectionException e) {
                return StatusCode(503, new { message = e.Message});
            }
        }

        [HttpPost]
        public async Task<IActionResult> TakePicture([Required]int id,
            [Required][Bind("ActionType")]DroneTakePictureRequest request) {
            try {
                var device = await _device_api.getDeviceById(id);
                await _device_connection_api.doDeviceAction(device, async client =>
                    await client.takePictureAsync(request, CancellationToken.None));
                return Ok();
            }
            catch (DeviceAuthorizationException e) {
                return Unauthorized(e.Message);
            }
            catch (DeviceConnectionException e) {
                return StatusCode(503, new { message = e.Message});
            }
        }

        public async Task<IActionResult> RecordVideo([Required]int id,
            [Required][Bind("ActionType")]DroneRecordVideoRequest request) {
            try {
                var device = await _device_api.getDeviceById(id);
                await _device_connection_api.doDeviceAction(device, async client =>

Areas/DHub/Views/Devices/Camera.cshtml
@model DroHub.Areas.DHub.Models.Device
@{
    ViewData["Title"] = "Camera";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Device
        <small>Camera</small>
    </h1>
    <ol class="breadcrumb">
        <li><a asp-area="DHub" asp-controller="Devices" asp-action="" title="Back to devices list"><i class="fa fa-camera"></i> Devices</a></li>
        <li class="active">Camera</li>
    </ol>
</section>
<!-- /Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#">Camera</a>
                            </li>
                            <li role="presentation">
                                <a asp-area="DHub" asp-controller="DeviceRepository" asp-route-id="@Model.Id" asp-action="Gallery" title="View device gallery">Gallery</a>
                            </li>
                            <li role="presentation">
                                <a asp-area="DHub" asp-controller="Devices" asp-route-id="@Model.Id" asp-action="Data" title="View device data">Data</a>
                            </li>
                            <li class="pull-right header">
                                <button class="btn btn-danger" title="Turn off the device">
                                    <i class="fa fa-power-off"></i>
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="box-body">
                    <div class="col-xs-2">

                    </div>
                    <div class="col-xs-8">
                        <div align="center" class="embed-responsive embed-responsive-16by9">
                            <video id="droneVideo" autoplay loop class="embed-responsive-item">
                                <source src="~/DemoContents/DJI Mavic Air live stream test.avi" type="video/mp4">
                            </video>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <form asp-action="Edit">
                            <label asp-for="ISO" class="control-label"></label>
                            <select asp-for="ISO" class="form-control select2" style="width: 100%;"
                                    asp-items="@(new SelectList((IEnumerable<SelectListItem>)@ViewData["Isos"], "Value" , "Text" ))"></select>
                            <span asp-validation-for="ISO" class="text-danger"></span>
                            <label asp-for="Apperture" class="control-label"></label>
                            <select asp-for="Apperture" class="form-control select2" style="width: 100%;"
                                    asp-items="@(new SelectList((IEnumerable<SelectListItem>)@ViewData["Appertures"], "Value", "Text"))"></select>
                            <span asp-validation-for="Apperture" class="text-danger"></span>
                            <label asp-for="FocusMode" class="control-label"></label>
                            <select asp-for="FocusMode" class="form-control select2" style="width: 100%;"
                                    asp-items="@(new SelectList((IEnumerable<SelectListItem>)@ViewData["FocusModes"], "Value", "Text"))"></select>
                            <span asp-validation-for="FocusMode" class="text-danger"></span>
                        </form>
                        <br />
                        <div class="text-center">
                            <a class="btn btn-app" onclick="playPause()">
                                <i id="iconPlayPause" class="fa fa-pause"></i>
                            </a>
                        </div>
                        <br />
                        <a class="btn btn-app btn-block">
                            <i class="fa fa-camera"></i> Take photo
                        </a>
                    </div>
                </div>
                <div class="box-footer">
                    <a asp-area="DHub" asp-controller="Devices" asp-action="" class="btn btn-primary" title="Back to devices list">Back to list</a>
                    <span class="pull-right">Telemetry info</span>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Main content -->
<script>
    function playPause() {
        var video = $('#droneVideo')[0];
        var iconPlayPause = $('#iconPlayPause');

        if (video.paused) {
            video.play();
        } else {
            video.pause();
        }

        iconPlayPause.toggleClass("fa-play");
        iconPlayPause.toggleClass("fa-pause");

    }
</script>

Areas/DHub/Views/Devices/Data.cshtml
@model DroHub.Areas.DHub.Models.Device
@{
    ViewData["Title"] = "Data";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Device
        <small>Data</small>
    </h1>
    <ol class="breadcrumb">
        <li><a asp-area="DHub" asp-controller="Devices" asp-action="" title="Back to devices list"><i class="fa fa-camera"></i> Devices</a></li>
        <li class="active">Data</li>
    </ol>
</section>
<!-- /Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li role="presentation">
                                <a asp-area="DHub" asp-controller="DeviceRepository" asp-route-id="@Model.Id" asp-action="Gallery" title="View device gallery">Gallery</a>
                            </li>
                            <li role="presentation" class="active">
                                <a href="#">Data</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="box-body">
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.SerialNumber)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.SerialNumber)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.CreationDate)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.CreationDate)
                        </dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.ISO)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.ISO)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Apperture)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Apperture)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.FocusMode)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.FocusMode)
                        </dd>
                    </dl>
                </div>
                <div class="box-footer">
                    <a asp-area="DHub" asp-controller="Devices" asp-action="" class="btn btn-primary" title="Back to devices list">Back to list</a>
                    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-success" title="Edit this device">Edit</a>
                    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger" title="Delete this device">Delete</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Main content -->

Areas/DHub/Views/Devices/Delete.cshtml
@model DroHub.Areas.DHub.Controllers.DevicesController.DeleteDeviceConfirmedModel
@{
    ViewData["Title"] = "Delete";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Devices
        <small>Delete</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-camera"></i> Devices</a></li>
        <li class="active">Delete</li>
    </ol>
</section>
<!-- /Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
            <div class="col-sm-6">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <div class="callout callout-danger" style="margin-bottom: 0!important;">
                            <h4><i class="fa fa-ban"></i> Are you sure?</h4>
                            Are you sure you want to delete this device?
                        </div>
                    </div>
                    <form asp-action="Delete">
                        <div class="box-body">
                            <div asp-validation-summary="All" class="text-danger content-centered"></div>
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Device.Name)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Device.Name)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Device.SerialNumber)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Device.SerialNumber)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Device.CreationDate)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Device.CreationDate)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.DeleteFlightSessions)
                                </dt>
                                <dd>
                                    <input type="checkbox" asp-for="DeleteFlightSessions"/>
                                </dd>
                            </dl>
                        </div>
                        <div class="box-footer text-right">
                            <input type="hidden" asp-for="Device.Id" />

                            <a asp-area="DHub" asp-controller="Devices" asp-action="" class="btn btn-warning" title="Back to devices list">Back to list</a>
                            <input type="submit" value="Delete" class="btn btn-danger" title="Delete this device" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
</section>

Areas/DHub/Views/Devices/Edit.cshtml
@model DroHub.Areas.DHub.Models.Device
@{
    ViewData["Title"] = "Edit";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Device
        <small>Edit</small>
    </h1>
    <ol class="breadcrumb">
        <li><a asp-area="DHub" asp-controller="Devices" asp-action="" title="Back to devices list"><i class="fa fa-camera"></i> Devices</a></li>
        <li class="active">Edit</li>
    </ol>
</section>
<!-- /Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-sm-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit Device</h3>
                </div>
                <form asp-action="Edit">
                    <div class="box-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input asp-for="Id" type="hidden" />
                        <input asp-for="CreationDate" type="hidden" />
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SerialNumber" class="control-label"></label>
                            <input asp-for="SerialNumber" class="form-control" />
                            <span asp-validation-for="SerialNumber" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="box-footer text-right">
                        <a asp-action="Delete" asp-route-id="@Model.Id"  class="btn btn-danger" title="Back to devices list">Delete Device</a>
                        <input type="submit" value="Save" title="Save device changes" class="btn btn-success" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- /Main content -->
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        //Initialize Select2 Elements
        $('.select2').select2()
    </script>
}

Areas/DHub/Views/Devices/Gallery.cshtml
@model DroHub.Areas.DHub.Controllers.DevicesController.GalleryPageModel
@{
    ViewData["Title"] = "Gallery";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <style>
        .box-top-border {
            border-top: 4px solid #3c8dbc
        }
    </style>
    <h1>
        Devices
        <small>Gallery</small>
    </h1>
    <ol class="breadcrumb">
        <li><a asp-area="DHub" asp-controller="Devices" asp-action="" title="Back to devices list"><i class="fa fa-camera"></i> Devices</a></li>
        <li class="active">Gallery</li>
    </ol>
</section>
<!-- /Content Header (Page header) -->
<!-- Main content -->
<section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title text-uppercase">Multimedia</h3>
                <div class="box-tools pull-right">
                        <button type="button" data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-minus"></i></button>
                    </div>
            </div>
            <div class="box-body">
                <ul class="timeline">
                    @foreach(var video_file in @Model.video_paths) {
                    <li>
                        <i class="fa fa-camera bg-maroon"></i>
                        <div class="timeline-item">

                            <h3 class="timeline-header">
                                <span class='time local-time-text' data-unix-time="@video_file.Name.Split('-')[2].Split('.')[0]"><i class="fa fa-clock-o"></i></span>
                            </h3>
                            <div class="timeline-body">
                                <div class="box box-solid collapsed-box">
                                    <div class="box-header">
                                        <div class="box-tools pull-right">
                                            <button type="button" data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </div>
                                    <div class="box-body">
                                        <div class="embed-responsive embed-responsive-16by9">
                                            @* <div class=device-video-overlay>
                                                <div class="video-overlay-top video-overlay-left">

                                                </div>
                                                <div class="video-overlay-top video-overlay-centered">
                                                    <i class="fa fa-play-circle"></i>
                                                </div>
                                            </div> *@
                                            <video class="rounded centered embed-responsive-item controls device-video livestream-recording-video" src='@Url.Action("GetLiveStreamRecordingVideo", new {video_id = video_file.Name})' controls preload="none" playsinline></video>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    }
                </ul>
            </div>
        </div>
        <div class="box box-top-border">
            <div class="box-header with-border">
                <h3 class="box-title text-uppercase">Logs</h3>
                <div class="box-tools pull-right">
                        <button type="button" data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-minus"></i></button>
                    </div>
            </div>
            <div class="box-body">
                Logs
            </div>
        </div>
</section>
@section Scripts {
    <script type="text/javascript" src="~/js/gallery.js"></script>
}